import { chromium } from 'playwright';
import { preview } from 'vite';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const server=await preview({preview:{host:'127.0.0.1',port:4173,strictPort:true}});
let browser;
try {
 browser=await chromium.launch({channel:'chrome',headless:true});
 await mkdir('artifacts',{recursive:true});
 const errors=[];
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error'&&/hydration|Minified React error/.test(m.text()))errors.push(m.text());});
 await page.goto('http://127.0.0.1:4173');
 await page.locator('#home h1').waitFor();
 await page.waitForTimeout(1600);
 assert.equal(await page.locator('main section[id]').count(),6);
 assert.match(await page.locator('.scene-caption').textContent(),/LIVE RENDER/);
 const demos=['https://contohcatalog.netlify.app/','https://creativeagen.netlify.app/','https://barbershop-xi-eight.vercel.app/','https://weddingbookingsistem.vercel.app/'];
 for(const href of demos) assert.ok(await page.locator(`.project-actions a[href="${href}"]`).count());

 // Check real optical scaling and the complete hold/release interaction.
 await page.getByRole('button',{name:'Kaca pembesar',exact:true}).waitFor();
 await page.evaluate(()=>{window.__contextEvents=[];window.addEventListener('contextmenu',e=>window.__contextEvents.push(e.defaultPrevented));});
 const heading=await page.locator('#home h1').boundingBox();
 await page.mouse.move(heading.x+heading.width*.35,heading.y+heading.height*.3);
 await page.mouse.down({button:'right'});await page.waitForTimeout(90);
 assert.equal(await page.locator('.magnifying-glass').getAttribute('data-active'),'true');
 assert.equal(await page.locator('.lens-copy [id]').count(),0);
 assert.equal(await page.locator('.lens-copy').evaluate(el=>el.inert),true);
 const originalWidth=await page.locator('#portfolio-content #home h1').evaluate(el=>el.getBoundingClientRect().width);
 const zoomedWidth=await page.locator('.lens-copy h1').evaluate(el=>el.getBoundingClientRect().width);
 assert.ok(Math.abs(zoomedWidth/originalWidth-1.75)<.01);
 const firstPosition=await page.locator('.magnifying-glass').evaluate(el=>el.style.transform);
 await page.mouse.move(heading.x+heading.width*.6,heading.y+heading.height*.7);await page.waitForTimeout(60);
 assert.notEqual(await page.locator('.magnifying-glass').evaluate(el=>el.style.transform),firstPosition);
 await page.screenshot({path:'artifacts/magnifier.png'});
 await page.evaluate(()=>window.scrollBy({top:120,behavior:'instant'}));await page.waitForTimeout(70);
 const fixedSource=await page.locator('#portfolio-content .navbar').boundingBox();
 const fixedCopy=await page.locator('.lens-copy .navbar').boundingBox();
 const lensCenter=await page.locator('.magnifying-glass').evaluate(el=>{const r=el.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};});
 assert.ok(Math.abs(fixedCopy.y-(lensCenter.y+1.75*(fixedSource.y-lensCenter.y)))<1);
 await page.mouse.up({button:'right'});
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
 assert.equal(await page.locator('.magnifying-glass').getAttribute('data-active'),'false');
 assert.equal(await page.locator('.lens-copy').count(),0);
 assert.ok(await page.evaluate(()=>window.__contextEvents.includes(true)));
 assert.equal(await page.locator('#home h1').evaluate(el=>{const e=new MouseEvent('contextmenu',{bubbles:true,cancelable:true,shiftKey:true,button:2});return el.dispatchEvent(e);}),true);
 assert.equal(await page.locator('a[href="#projects"]').first().evaluate(el=>{const e=new MouseEvent('contextmenu',{bubbles:true,cancelable:true,button:2});return el.dispatchEvent(e);}),true);
 const magnifierButton=page.getByRole('button',{name:'Kaca pembesar',exact:true});
 await magnifierButton.click();assert.equal(await magnifierButton.getAttribute('aria-pressed'),'true');
 const keyboardPosition=await page.locator('.magnifying-glass').evaluate(el=>el.style.transform);
 await page.keyboard.press('ArrowRight');
 assert.notEqual(await page.locator('.magnifying-glass').evaluate(el=>el.style.transform),keyboardPosition);
 await page.keyboard.press('Escape');assert.equal(await magnifierButton.getAttribute('aria-pressed'),'false');
 await magnifierButton.click();await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
 assert.equal(await page.locator('.magnifying-glass').getAttribute('data-active'),'false');
 const flightBefore=await page.locator('.paper-plane').evaluate(el=>el.style.transform);
 await page.evaluate(()=>window.scrollTo({top:document.getElementById('skills').offsetTop,behavior:'instant'}));await page.waitForTimeout(500);
 assert.notEqual(await page.locator('.paper-plane').evaluate(el=>el.style.transform),flightBefore);
 assert.equal(await page.locator('.paper-plane').getAttribute('data-visible'),'true');
 assert.ok(await page.locator('.flight-trail path').getAttribute('d'));
 await page.screenshot({path:'artifacts/paper-flight.png'});
 await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo({top:0,behavior:'instant'});});await page.waitForTimeout(300);
 await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
 await page.screenshot({path:'artifacts/hero-desktop.png'});
 await page.locator('#projects').scrollIntoViewIfNeeded();
 await page.getByRole('button',{name:'Frontend',exact:true}).last().click();
 await page.waitForTimeout(400);assert.equal(await page.locator('.project-card').count(),2);
 await page.getByRole('button',{name:'Backend',exact:true}).last().click();
 await page.waitForTimeout(400);assert.equal(await page.locator('.project-card').count(),0);assert.ok(await page.getByRole('status').isVisible());
 await page.getByRole('button',{name:'Lihat semua project'}).click();
 await page.waitForTimeout(400);assert.equal(await page.locator('.project-card').count(),4);
 await page.getByRole('button',{name:'Case study',exact:false}).first().click();
 assert.ok(await page.locator('.case-dialog').isVisible());
 assert.equal(await page.locator('.case-dialog h2').textContent(),'Contoh Catalog');
 await page.keyboard.press('Escape');assert.ok(!await page.locator('.case-dialog').count());
 await page.keyboard.press('Control+k');assert.ok(await page.locator('.palette').isVisible());
 await page.locator('#command').fill('contact');assert.equal(await page.locator('.palette a').count(),1);
 await page.locator('.palette a').click();assert.ok(!await page.locator('.palette').isVisible());
 const mobile=await browser.newPage({viewport:{width:375,height:812},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
 mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.goto('http://127.0.0.1:4173');await mobile.waitForTimeout(700);
 assert.ok(await mobile.locator('.static-core').isVisible());
 assert.equal(await mobile.getByRole('button',{name:'Kaca pembesar',exact:true}).count(),0);
 assert.ok(!await mobile.locator('.flight-layer').isVisible());assert.equal(await mobile.locator('canvas').count(),0);
 assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await mobile.getByRole('button',{name:'Toggle navigation'}).click();
 assert.ok(await mobile.locator('nav').isVisible());await mobile.locator('nav a[href="#projects"]').click();assert.ok(!await mobile.locator('nav').isVisible());
 await mobile.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});
 await mobile.screenshot({path:'artifacts/mobile.png',fullPage:true});
 await mobile.screenshot({path:'artifacts/hero-mobile.png'});
 await mobile.setViewportSize({width:812,height:375});assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));

 const touchPage=await browser.newPage({viewport:{width:375,height:812},isMobile:true,hasTouch:true,reducedMotion:'no-preference'});
 touchPage.on('pageerror',e=>errors.push(e.message));
 await touchPage.goto('http://127.0.0.1:4173');await touchPage.waitForTimeout(700);
 assert.equal(await touchPage.getByRole('button',{name:'Kaca pembesar',exact:true}).count(),0);
 assert.ok(await touchPage.locator('#about .section-heading').evaluate(el=>el.classList.contains('reveal-pending')));
 await touchPage.touchscreen.tap(190,180);
 assert.ok(await touchPage.locator('.mobile-ink-ring').evaluate(el=>el.getAnimations().length>0));
 await touchPage.waitForTimeout(450);
 await touchPage.evaluate(()=>{const args={pointerType:'touch',pointerId:4,isPrimary:true};window.dispatchEvent(new PointerEvent('pointerdown',{...args,clientX:100,clientY:100}));window.dispatchEvent(new PointerEvent('pointermove',{...args,clientX:100,clientY:180}));window.dispatchEvent(new PointerEvent('pointerup',{...args,clientX:100,clientY:180}));});
 assert.equal(await touchPage.locator('.mobile-ink-ring').evaluate(el=>el.getAnimations().length),0);
 const touchMenu=touchPage.getByRole('button',{name:'Toggle navigation'});
 await touchMenu.tap();assert.equal(await touchMenu.getAttribute('aria-expanded'),'true');
 assert.equal(await touchPage.evaluate(()=>document.body.style.overflow),'hidden');
 await touchPage.waitForTimeout(40);
 assert.ok(await touchPage.locator('.nav-panel').evaluate(el=>el.getAnimations().length>0));
 await touchPage.waitForTimeout(350);assert.equal(await touchPage.locator('nav a:visible').count(),6);
 assert.ok(await touchPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await touchPage.screenshot({path:'artifacts/mobile-menu.png'});
 await touchPage.touchscreen.tap(20,700);await touchPage.waitForTimeout(350);
 assert.equal(await touchMenu.getAttribute('aria-expanded'),'false');
 assert.ok(!await touchPage.locator('nav').isVisible());assert.equal(await touchPage.evaluate(()=>document.body.style.overflow),'');
 await touchMenu.tap();await touchPage.keyboard.press('Escape');await touchPage.waitForTimeout(350);
 assert.equal(await touchMenu.getAttribute('aria-expanded'),'false');assert.ok(await touchMenu.evaluate(el=>el===document.activeElement));
 await touchMenu.tap();await touchMenu.tap();await touchMenu.tap();await touchPage.waitForTimeout(350);
 assert.equal(await touchMenu.getAttribute('aria-expanded'),'true');
 await touchPage.locator('nav a[href="#about"]').tap();await touchPage.waitForTimeout(900);
 assert.equal(await touchMenu.getAttribute('aria-expanded'),'false');
 assert.ok(!await touchPage.locator('#about .section-heading').evaluate(el=>el.classList.contains('reveal-pending')));
 assert.notEqual(await touchPage.locator('.nav-reading-progress').evaluate(el=>el.style.transform),'scaleX(0)');
 await touchMenu.tap();await touchPage.setViewportSize({width:812,height:375});await touchPage.waitForTimeout(350);
 assert.equal(await touchPage.evaluate(()=>document.body.style.overflow),'');assert.ok(await touchPage.locator('nav').isVisible());
 await touchPage.setViewportSize({width:320,height:640});await touchMenu.tap();await touchPage.waitForTimeout(350);
 assert.ok(await touchPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await touchPage.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await touchPage.locator('.nav-panel').evaluate(el=>el.getAnimations().length),0);
 assert.equal(await touchPage.locator('.reveal-pending').count(),0);
 await touchPage.close();
 const noGl=await browser.newPage();await noGl.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type.startsWith('webgl'))return null;return original.call(this,type,...args);};});
 await noGl.goto('http://127.0.0.1:4173');await noGl.waitForTimeout(800);assert.ok(await noGl.locator('.static-core').isVisible());assert.equal(await noGl.locator('.project-card').count(),4);
 const noJs=await browser.newPage({javaScriptEnabled:false});await noJs.goto('http://127.0.0.1:4173');assert.equal(await noJs.locator('main section[id]').count(),6);assert.equal(await noJs.locator('.project-actions a').count(),4);
 await page.emulateMedia({reducedMotion:'reduce'});assert.ok(!await page.locator('.flight-layer').isVisible());
 await page.emulateMedia({reducedMotion:'no-preference'});
 assert.deepEqual(errors,[]);
 console.log('PASS: six sections, preserved demo URLs, filters, case study/Escape, command palette, mobile menu, reduced motion, no horizontal overflow, WebGL fallback, prerender without JS, no runtime/hydration errors, 1.75x magnifier/right-hold/pointer/keyboard/blur, native context menus, paper-plane scroll and reduced motion, animated mobile menu/rapid toggle/outside tap/Escape/resize, touch ripple/swipe cancellation, reveals and reading progress.');
} finally {await browser?.close();await new Promise(resolve=>server.httpServer.close(resolve));}
